services:
  relatoriosapi:
    container_name: relatoriosapi_desenvolvimento
    build:
      context: .
      dockerfile: docker/desenvolvimento/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
